### ISSUE TITLE
Documented syntax for select query doesn't work

### ISSUE THREAD

**Issue by joelbarker2011** [orator-orm/docs#2]
This could be considered a bug in the documentation, a bug in Orator's code, or (possibly) a bug in PyMySQL.

[Orator's documentation states](https://github.com/orator-orm/docs/blob/master/basic_usage.rst#running-a-select-query):

> ### Running a select query
> 
> ```
> results = db.select('select * from users where id = ?', [1])
> ```
> 
> The `select` method will always return a list of results.
> ### Running an insert statement
> 
> ```
> db.insert('insert into users (id, name) values (?, ?)', [1, 'John'])
> ```
> ### Running an update statement
> 
> ```
> db.update('update users set votes = 100 where name = ?', ['John'])
> ```

However, attempting to use this syntax with the PyMySQL adapter results in errors.

On insert:

```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    db.insert('insert into widgets (id) values (?)', [42])
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 213, in insert
    return self.statement(query, bindings)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 318, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not all arguments converted during string formatting (SQL: insert into widgets (id) values (?) ([42]))
```

On select:

```
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    db.select('select * from widgets where id = ?', [42])
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 318, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not all arguments converted during string formatting (SQL: select * from widgets where id = ? ([42]))
```

On update:

```
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    db.update('update widgets set id = 43 where id = ?', [42])
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 216, in update
    return self.affecting_statement(query, bindings)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 318, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not all arguments converted during string formatting (SQL: update widgets set id = 43 where id = ? ([42]))
```

The queries work when replacing `?` with `%s`. This is due to how PyMySQL handles strings in its [Cursor.execute method](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/cursors.py#L150):

```
    If args is a list or tuple, %s can be used as a placeholder in the query.
    If args is a dict, %(name)s can be used as a placeholder in the query.
```

I'm not sure what the best solution here would be. I haven't tested with the other database adapters (Postgres or Sqlite). Ideally, all adapters would work the same way (I personally would prefer `?` replacements, to match Ruby on Rails' ActiveRecord style).

**Comment by joelbarker2011** [comment]
My test script (comment/uncomment lines to try different queries):

``` python
# test.py
from os import environ as env

from orator import DatabaseManager
from orator import Model
from orator import Schema

if __name__ == '__main__':
    config = {
        'mytestdb': {
            'driver': 'mysql',
            'user': env['DB_USER'],
            'password': env['DB_PASS'],
            'host': env.get('DB_HOST', 'localhost'),
            'database': env['DB_NAME']
        }
    }

    db = DatabaseManager(config)
    Model.set_connection_resolver(db)
    schema = Schema(db)

    schema.drop_if_exists('widgets')

    with schema.create('widgets') as t:
        t.increments('id')

    # try insert
    db.insert('insert into widgets (id) values (?)', [42])

    # try select
    #class Widget(Model):
    #    __guarded__ = []
    #    __timestamps__ = False
    #    pass
    #Widget.create(id=42)
    #db.select('select * from widgets where id = ?', [42])

    # try update
    #db.update('update widgets set id = 43 where id = ?', [42])

# run with:
# DB_USER=mydbuser DB_PASS=mydbpass DB_NAME=mydatabase python test.py
```

**Comment by sdispater** [comment]
It's a limitation of how DB API packages work. Each package can choose between various `paramstyle` value to represent parameters (`qmark`, `numeric`, `named`, `format`, `pyformat`).

So, basically, SQL queries depend on the backend you use.

I'm trying to figure out a way to be able to use only one parameter style (`qmark` most likely)

**Comment by sdispater** [comment]
I will add a note in the documentation to point out this fact.
